### PR TITLE
fix links to documentation

### PR DESCRIPTION
**Pull request by hkollmann**

### CODE REVIEW

**Comment by cboulanger** [comment]
In principle, there is no need to change this, /docs/ should continue to work, if not, the script in `404.html` is not yet updated...

**Comment by cboulanger** [comment]
On the other hand, it doesn't hurt to change it.

**Comment by hkollmann** [comment]
Keep it simple and use the direct link. Works without 404.html magic.
That's why i changed it.

**Comment by hkollmann** [comment]
Hey the preview feature is great!!!!

**Comment by cboulanger** [comment]
I now remember why it's important not to change the `apps://` pseudo-protocol - the documentation must work online and offline (i.e. on the website and in the `qx serve` application server). The links to the apps will be resolved differently in both cases, so that's why that magic needs to stay. Also, it will ensure that the markdown URL-linter will not check these links.

**Comment by cboulanger** [comment]
Yes, I like that, too, including the bot comment. Powered by GitHub actions. Very cool.

**Comment by hkollmann** [comment]
But that's a documentation issue - not a website issue.

**Comment by cboulanger** [comment]
Oh you're right. Wrong issue.

**Pull request closed without merging**
